development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://aiqauizpmgqsya:jycC4m_yJ5rGYxXAj2G1V0lWRj@ec2-54-225-101-191.compute-1.amazonaws.com:5432/d4uvthtee58tpv
